#Base CircleCI template for Maven projects.
#Defined below are steps for building, unit tests, OWasp, Sonar, and release tag

version: 2.1
jobs:
  inc_build:
    docker: &image
      - image: circleci/openjdk:11-jdk
    steps:
      - run: &env
          name: Setting environment
          command: |
            echo "export RELEASE=0" >> $BASH_ENV
            echo "export RELEASE_VERSION=NA" >> $BASH_ENV
            echo "export RELEASE_TAG=NA" >> $BASH_ENV
            echo "export NEXT_VERSION=NA" >> $BASH_ENV

            echo "export GPG_KEYRING=$RELEASE_KEY" >> $BASH_ENV
            echo "export DISABLE_DOWNLOAD_PROGRESS_OPTS=-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn" >> $BASH_ENV
            echo "export LINUX_MVN_RANDOM=-Djava.security.egd=file:/dev/./urandom" >> $BASH_ENV
            echo "export COVERAGE_EXCLUSIONS=**/test/**/*,**/itests/**/*,**/*Test*,**/sdk/**/*,**/*.js,**/node_modules/**/*,**/jaxb/**/*,**/wsdl/**/*,**/nces/sws/**/*,**/*.adoc,**/*.txt,**/*.xml" >> $BASH_ENV
            echo "export GITHUB_USERNAME=connexta" >> $BASH_ENV
            echo "export GITHUB_REPONAME=ion-index-api" >> $BASH_ENV
            echo "export GITHUB_KEY={change-me}" >> $BASH_ENV
            source $BASH_ENV
      - checkout
      - run:
          name: Building
          command: |
            mvn install -B -DskipTests $DISABLE_DOWNLOAD_PROGRESS_OPTS
            mvn clean install -B -Dgib.enabled=true -Dgib.referenceBranch=/refs/remotes/origin/$CHANGE_TARGET $DISABLE_DOWNLOAD_PROGRESS_OPTS

  test:
    docker: *image
    steps:
      - run: *env
      - checkout
      - run:
          name: Building
          command: |
            if [ $RELEASE = true ]
            then
              mvn -B -Dtag=$RELEASE_TAG -DreleaseVersion=$RELEASE_VERSION -DdevelopmentVersion=$NEXT_VERSION -Dgpg.secretKeyring=$GPG_KEYRING -Dgpg.publicKeyring=$ION_GPG_KEYRING release:prepare
              echo "export RELEASE_CONFIG = `git rev-parse HEAD`" >> $BASH_ENV
            else
              mvn clean install -B $DISABLE_DOWNLOAD_PROGRESS_OPTS
            fi
            mvn test
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
  owasp:
    docker: *image
    steps:
      - run: *env
      - checkout
      - run:
          name: Owasp Tests
          command: |
            if [ $CIRCLE_PR_NUMBER ]
            then
              mvn install -B -Powasp -DskipTests -Dgib.enabled=true -Dgib.referenceBranch=/refs/remotes/origin/$CHANGE_TARGET -nsu $DISABLE_DOWNLOAD_PROGRESS_OPTS
            else
              mvn install -B -Powasp -DskipTests -nsu $DISABLE_DOWNLOAD_PROGRESS_OPTS
            fi
            cp **/dependency-check-report.* /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
  sonar:
    docker: *image
    steps:
      - run: *env
      - checkout
      - run:
          name: Sonar check
          command: |
            if [ $CIRCLE_BRANCH = master ]
            then
              if [ $RELEASE = true ]
              then
                git checkout $RELEASE_TAG
              fi
              mvn -q -B install sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN  -Dsonar.organization=cx -Dsonar.projectKey=$GITHUB_REPONAME -Dsonar.exclusions=$COVERAGE_EXCLUSIONS $DISABLE_DOWNLOAD_PROGRESS_OPTS -Dsonar.pullrequest.key=${CIRCLE_PULL_REQUEST##*/} -Dsonar.pullrequest.branch=${CIRCLE_BRANCH} -Dsonar.pullrequest.base=master
            fi
  release_tag:
    docker: *image
    steps:
      - run: *env
      - checkout
      - run:
          name: Release Tag
          command: |
            if [ $RELEASE = true ]
            then
              git checkout $RELEASE_COMMIT
              git remote add ssh-origin git@github.com:connexta/$CIRCLE_PROJECT_REPONAME.git
              echo ssh -i $GITHUB_KEY -l git -o StrictHostKeyChecking=no \\"\\$@\\" > run_ssh.sh
              chmod +x run_ssh.sh
              git push ssh-origin HEAD:$CIRCLE_BRANCH && git push ssh-origin $RELEASE_TAG
            fi
  deploy:
    docker: *image
    steps:
      - run: *env
      - checkout
      - run:
          name: Deploy
          command: |
            if [ $RELEASE = true ]
            then
              git checkout $RELEASE_TAG
            fi
            mvn javadoc:aggregate -B -DskipTests -nsu $DISABLE_DOWNLOAD_PROGRESS_OPTS
            if [ $RELEASE = true]
            then
              mvn deploy -B -DskipTests -DretryFailedDeploymentCount=10 -nsu $DISABLE_DOWNLOAD_PROGRESS_OPTS -Dgpg.secretKeyring=$GPG_KEYRING -Dgpg.publicKeyring=$GPG_KEYRING -Dgpg.passphraseServerId=\"ion-signing\"
            else
              mvn deploy -B -DskipTests -DretryFailedDeploymentCount=10 -nsu $DISABLE_DOWNLOAD_PROGRESS_OPTS
            fi

workflows:
  version: 2.1
  default:
    jobs:
      - inc_build
      - test:
          requires:
            - inc_build
      - owasp:
          requires:
            - test
      - sonar:
          requires:
            - owasp
      - release_tag:
          requires:
            - sonar